### ISSUE TITLE
 vWii Region Check Bug

### ISSUE THREAD

**Issue by Ingunar** [modmii/Some-YAWMM-Mod#2]
`Couldn't find the region of this system` message at the start, or during the install/uninstall, no matter if WAD is the correct region or not.
*This is a vWii-only Bug, and was discussed on Discord already*

![1689427080798](https://github.com/modmii/YAWM-ModMii-Edition/assets/120290867/e0f2c4ab-91a9-42aa-a8fe-568dbcf91f2b)
![image0000001001](https://github.com/modmii/YAWM-ModMii-Edition/assets/120290867/cffa5ec5-858a-4781-8390-43e3265db805)

**Comment by EldosHD** [comment]
Is there an update on this? I have a similar issue
